# Generated by Django 5.1.1 on 2024-09-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=300)),
                ('overall_rating', models.FloatField()),
                ('reviews', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
