# Generated by Django 5.1 on 2024-09-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="website",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
