# Generated by Django 5.1 on 2024-09-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodie", "0002_alter_restaurant_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
