# Generated by Django 5.1 on 2024-09-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodie", "0002_alter_restaurant_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
