# Generated by Django 5.1.1 on 2024-09-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='street',
            new_name='city',
        ),
    ]
